before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: WC631yiTfwleH/9S5RgH25kSpr8dBdYobBLqNGSi7ckfM0O7lIKCy0Hwf/Hv9e8X6UwbgINEivPedrvE3c2gj4jOeyZvyhkXyt6nrtjRNmdhB39Fsda6bzGntKq6/8bV8KxJ12ljF2q76SmcY1HeW+/Kw2F4ZcyZvXrg+U4d0i4ceeI40JStA3zl5Bzrv9xzXdq9d+zildb/xmoBeiCVVCaSoOz3QlpMQwIkEgXnow0sXyVRYAeH9ZV3+WV6/amsrCE4LpDB0Bxl/uqSNOU4w4VK5KVyVaDaZpB5lh0mNAfsblWcWQbMaHcgkFuUFKQgCzCckL7h9OUkEvBefPbi6NYutZhVYQpTKNU5A/dTE5D2bTnCrr+dL7lcOJ0taUp15TrckLUbXPm1AH8+9tETUeerDZ1wSpWQqus7vAw7gaSKPMsCsoe6gOxL/gVwaM26r/pxh5l4SYUOefj5CUg6ZlJJG/bqBDXCcxJKf+CkcCdgPxZcgRPz/ILa/PWXVDmNL1xKSNo2VmxQ/77fc5FuUPkfP1pyzGaXFjb+vKTLdanQIQ6aFH+nx2ZcoWdNoxiF2qg7NBQRcscAPgj34JA//dwfU/mB2XNRYyqd10iBrEGvRsp8ZNvHTPW/JOcYWtsFKnKUZk67R7Aah+w1d+9FIbyUgqqVXNEuShTmsAa1kWM= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
